/**
 * AWSECommerceServicePortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.amazon.webservices.AWSECommerceService._2013_08_01;

public interface AWSECommerceServicePortType extends java.rmi.Remote {
    public void itemSearch(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String XMLEscaping, java.lang.String validate, com.amazon.webservices.AWSECommerceService._2013_08_01.ItemSearchRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.ItemSearchRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.ItemsArrayHolder items) throws java.rmi.RemoteException;
    public void itemLookup(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.ItemLookupRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.ItemLookupRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.ItemsArrayHolder items) throws java.rmi.RemoteException;
    public void browseNodeLookup(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.BrowseNodeLookupRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.BrowseNodeLookupRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.BrowseNodesArrayHolder browseNodes) throws java.rmi.RemoteException;
    public void similarityLookup(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.SimilarityLookupRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.SimilarityLookupRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.ItemsArrayHolder items) throws java.rmi.RemoteException;
    public void cartGet(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.CartGetRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.CartGetRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartAdd(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.CartAddRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.CartAddRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartCreate(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.CartCreateRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.CartCreateRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartModify(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.CartModifyRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.CartModifyRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartClear(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService._2013_08_01.CartClearRequest shared, com.amazon.webservices.AWSECommerceService._2013_08_01.CartClearRequest[] request, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2013_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
}
